console.log(Math.PI);
// console.log(Math.trunc(Math.PI));
// console.log(Math.round(Math.PI));
// console.log(Math.round(3.5 ));
// console.log(Math.ceil(3.5 ));
// console.log(Math.floor(3.5 ));
// console.log(Math.pow(2,4));
// console.log(Math.min(2,4,6));
// console.log(Math.max (2,4,6));
console.log(Math.random());
console.log(Math.floor(Math.random() * 10)+1);